development:
  host: localhost
  database: shortly_development

test:
  host: localhost
  database: shortly_test

# set these environment variables on your prod server
<% uri = URI.parse(ENV['MONGOHQ_URL']) %>
production:
  host: <%= uri.host %>
  port: <%= uri.port %>
  username: <%= uri.user %>
  password: <%= uri.password %>
  database: <%= uri.path.sub('/','') %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
